// AUTO-GENERATED by packages/shared-types/scripts/generate.py.
// DO NOT EDIT BY HAND. Run the generator and commit the output:
//   python packages/shared-types/scripts/generate.py
// CI verifies no drift between this file and the engine source.

export type RiskTolerance = "conservative" | "moderate" | "aggressive";

export const RiskTolerance = {
  CONSERVATIVE: "conservative",
  MODERATE: "moderate",
  AGGRESSIVE: "aggressive",
} as const;

export type IncomeNeed = "low" | "medium" | "high";

export const IncomeNeed = {
  LOW: "low",
  MEDIUM: "medium",
  HIGH: "high",
} as const;

export type ProfileStyle = "income" | "balanced" | "growth";

export const ProfileStyle = {
  INCOME: "income",
  BALANCED: "balanced",
  GROWTH: "growth",
} as const;

export interface UserStrategyProfile {
  risk_tolerance: RiskTolerance;
  income_need: IncomeNeed;
  max_position_pct: number;
  max_coverage_pct: number;
  min_iv_rank_for_short_premium: number;
  prefer_collars_over_covered_calls: boolean;
  drawdown_tolerance?: number;
  style?: ProfileStyle;
}
