// AUTO-GENERATED by packages/shared-types/scripts/generate.py.
// DO NOT EDIT BY HAND. Run the generator and commit the output:
//   python packages/shared-types/scripts/generate.py
// CI verifies no drift between this file and the engine source.

export type Regime = "HIGH_IV_EVENT" | "HIGH_IV_PIN" | "LOW_IV_TREND" | "LOW_IV_RANGE" | "BREAKOUT" | "POST_EVENT_REPRICE";

export const Regime = {
  HIGH_IV_EVENT: "HIGH_IV_EVENT",
  HIGH_IV_PIN: "HIGH_IV_PIN",
  LOW_IV_TREND: "LOW_IV_TREND",
  LOW_IV_RANGE: "LOW_IV_RANGE",
  BREAKOUT: "BREAKOUT",
  POST_EVENT_REPRICE: "POST_EVENT_REPRICE",
} as const;

export const REGIME_COLORS: Readonly<Record<Regime, string>> = {
  HIGH_IV_EVENT: "amber",
  HIGH_IV_PIN: "slate",
  LOW_IV_TREND: "emerald",
  LOW_IV_RANGE: "sky",
  BREAKOUT: "violet",
  POST_EVENT_REPRICE: "rose",
} as const;
