// AUTO-GENERATED by packages/shared-types/scripts/generate.py.
// DO NOT EDIT BY HAND. Run the generator and commit the output:
//   python packages/shared-types/scripts/generate.py
// CI verifies no drift between this file and the engine source.

export type OptionType = "CALL" | "PUT";

export const OptionType = {
  CALL: "CALL",
  PUT: "PUT",
} as const;

export interface OptionContract {
  underlying: string;
  expiry: string;
  strike: number;
  option_type: OptionType;
  mid?: number | null;
  bid?: number | null;
  ask?: number | null;
  iv?: number | null;
  open_interest: number;
  volume: number;
}

export interface ChainSnapshot {
  underlying: string;
  spot: number;
  as_of: string;
  contracts: readonly OptionContract[];
}
