// AUTO-GENERATED by packages/shared-types/scripts/generate.py.
// DO NOT EDIT BY HAND. Run the generator and commit the output:
//   python packages/shared-types/scripts/generate.py
// CI verifies no drift between this file and the engine source.

export type PRetryBasis = "empirical" | "blend";

export const PRetryBasis = {
  EMPIRICAL: "empirical",
  BLEND: "blend",
} as const;

export interface YearlineContext {
  as_of: string | null;
  ticker: string | null;
  schema_version: string | null;
  model_stack_version: string | null;
  adapter_version: string;
  repair_active: boolean;
  distance_to_ma250_pct?: number | null;
  required_rebound_to_ma250_pct?: number | null;
  post_confirmation_trend_state?: string | null;
  p_retry?: Readonly<Record<string, number>>;
  p_retry_basis?: PRetryBasis | null;
  gate_passed?: Readonly<Record<string, boolean>>;
  days_to_touch_central?: number | null;
  days_to_touch_low?: number | null;
  days_to_touch_high?: number | null;
  p_success?: number | null;
  success_gate_passed?: boolean;
  p_successful_reclaim?: Readonly<Record<string, number | null>>;
  reference_scope?: string | null;
  is_stale: boolean;
  must_not_auto_execute?: true;
}
