"""Byte-idempotency guard for the regeneration script.

Running `regenerate_decision_goldens.py --all` twice in succession must
produce identical files. Catches cross-environment nondeterminism (dict
ordering, frozenset iteration order, etc.) before it lands in a fixture.

When fewer than the full 12 fixtures have populated `inputs.json` files,
this test soft-skips so it doesn't gate the staged authoring cycle.
"""

from __future__ import annotations

import importlib
import sys
from pathlib import Path

import pytest

from tests._golden_helpers import GOLDENS_DIR, PLACEHOLDER_MARKER, list_fixtures


def _has_real_expected(fixture_dir: Path) -> bool:
    p = fixture_dir / "expected.json"
    if not p.exists():
        return False
    return PLACEHOLDER_MARKER not in p.read_text()


def test_regenerate_is_byte_idempotent(tmp_path: Path) -> None:
    """For each populated fixture, regenerate-to-tmp twice and compare bytes."""
    populated = [
        GOLDENS_DIR / name
        for name in list_fixtures()
        if (GOLDENS_DIR / name / "inputs.json").exists()
        and _has_real_expected(GOLDENS_DIR / name)
    ]
    if not populated:
        pytest.skip(
            "No fixtures with populated expected.json yet. "
            "Run regenerate_decision_goldens.py --all to populate the suite "
            "and re-enable this guard."
        )

    # Import the regen module's regenerate() function. The script lives
    # under packages/engine/scripts/ which is sibling to tests/. Use a
    # path-injection that survives running pytest from either packages/engine
    # or repo root.
    scripts_dir = (Path(__file__).resolve().parent.parent / "scripts").resolve()
    if str(scripts_dir) not in sys.path:
        sys.path.insert(0, str(scripts_dir))
    regen = importlib.import_module("regenerate_decision_goldens")

    for fixture_dir in populated:
        # Read the on-disk expected.json (the committed bytes).
        on_disk = (fixture_dir / "expected.json").read_text()

        # Regenerate via the public regenerate(name, out_dir) entry point.
        first = regen.regenerate(fixture_dir.name, out_dir=tmp_path / "first")
        second = regen.regenerate(fixture_dir.name, out_dir=tmp_path / "second")

        assert first == second, (
            f"{fixture_dir.name}: regeneration is NOT byte-idempotent "
            f"(first vs second run differ). Likely a nondeterministic "
            f"set/dict iteration somewhere in serialize_canonical or the "
            f"engine. Diff (truncated):\n"
            f"  first[:500]:  {first[:500]!r}\n"
            f"  second[:500]: {second[:500]!r}"
        )

        # Also assert the regenerated bytes match the on-disk committed bytes.
        # If this fails the committed fixture is stale — re-run the regen
        # script and commit.
        assert first == on_disk, (
            f"{fixture_dir.name}: regenerated bytes don't match committed "
            f"expected.json. The fixture is stale — run\n"
            f"    cd packages/engine && uv run python scripts/regenerate_decision_goldens.py --fixture {fixture_dir.name}\n"
            f"and commit the result. (This often indicates an engine\n"
            f"change that wasn't accompanied by a fixture regen.)"
        )


# Round-trip-via-loader test
def test_loaded_inputs_produce_real_dataclasses() -> None:
    """Round-trip: a fixture's inputs.json loads into the expected dataclass types.

    Skips fixtures without inputs.json. Useful as an early smoke test that
    inputs.json schema is well-formed before running the full replay.
    """
    from engine.flow_score.types import FlowScore  # noqa: PLC0415
    from engine.market_state.classify import MarketStateResult  # noqa: PLC0415
    from engine.profiles import UserStrategyProfile  # noqa: PLC0415
    from engine.recommendation import PositionState  # noqa: PLC0415
    from engine.types import ChainSnapshot  # noqa: PLC0415
    from tests._golden_helpers import load_inputs  # noqa: PLC0415

    seen = 0
    for name in list_fixtures():
        path = GOLDENS_DIR / name / "inputs.json"
        if not path.exists():
            continue
        seen += 1
        inputs = load_inputs(path)
        assert isinstance(inputs["chain_snapshot"], ChainSnapshot), name
        assert isinstance(inputs["positions"], PositionState), name
        assert isinstance(inputs["profile"], UserStrategyProfile), name
        assert isinstance(inputs["market_state"], MarketStateResult), name
        assert isinstance(inputs["flow_score"], FlowScore), name

    if seen == 0:
        pytest.skip("No fixtures with inputs.json yet.")
