#!/usr/bin/env python3
"""Generate TypeScript types from `packages/engine/engine/{regimes,profiles,types}.py`.

This script walks the locked Pydantic models + StrEnums in the engine package
and emits deterministic TS to `packages/shared-types/src/`. It is the canonical
SSOT bridge for ADR-0002 (Regime taxonomy) and ADR-0005 (engine purity boundary).

Usage
-----
  python packages/shared-types/scripts/generate.py            # writes .ts files
  python packages/shared-types/scripts/generate.py --check    # exits non-zero on drift

CI runs `--check` mode (see .github/workflows/ci.yml). If `--check` fails, run
the script without `--check`, commit the regenerated .ts, push.

Why a custom generator (not pydantic-to-typescript)?

  - The shared-types surface is small (3 models + 3 enums in M0.6). A focused
    generator is ~150 LOC vs. pulling in a Node runtime (json-schema-to-typescript)
    or a heavier Python lib (datamodel-code-generator) and configuring it.
  - Deterministic output (sorted keys, stable formatting) is crucial for the
    drift check; off-the-shelf tools often emit non-deterministic JSON.
  - We intentionally don't try to be general — adding a new model adds an
    explicit `_emit_*` block here, which forces a contributor to think about
    the cross-language coupling (per ADR-0002).
"""

from __future__ import annotations

import sys
import types
import typing
from enum import EnumMeta as EnumType  # EnumMeta is the portable alias (== EnumType in 3.11+)
from pathlib import Path
from typing import Any, get_args, get_origin

# `typing.Union` and `types.UnionType` (3.10+) are both valid origins for a
# union annotation, depending on Python version + how the annotation was written:
#   * Python 3.9:  Union[X, Y] / X | Y both surface as `typing.Union`
#   * Python 3.10+: X | Y produces `types.UnionType`; Union[X, Y] keeps `typing.Union`
#   * Python 3.14: typing.Union became a class (PEP changes); `str(origin)` is now
#                  `"<class 'typing.Union'>"` not `"typing.Union"`. Using `is` /
#                  `in` against the singleton is the version-stable check.
_UNION_ORIGINS: tuple[Any, ...] = (typing.Union,)
if hasattr(types, "UnionType"):
    _UNION_ORIGINS = _UNION_ORIGINS + (types.UnionType,)

# Make `engine` importable when invoked from the repo root or any nested dir.
_REPO_ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(_REPO_ROOT / "packages" / "engine"))

from pydantic import BaseModel  # noqa: E402

from engine import profiles, regimes, types  # noqa: E402

OUT_DIR = _REPO_ROOT / "packages" / "shared-types" / "src"

HEADER = """// AUTO-GENERATED by packages/shared-types/scripts/generate.py.
// DO NOT EDIT BY HAND. Run the generator and commit the output:
//   python packages/shared-types/scripts/generate.py
// CI verifies no drift between this file and the engine source.

"""


# --------------------------------------------------------------------------
# Type mapping
# --------------------------------------------------------------------------


def _ts_type(annotation: Any) -> str:
    """Map a Python annotation to a TS type string. Deterministic by construction."""
    # Plain types --------------------------------------------------------
    if annotation is str:
        return "string"
    if annotation is int or annotation is float:
        return "number"
    if annotation is bool:
        return "boolean"

    # date / datetime serialize to ISO strings over JSON ----------------
    name = getattr(annotation, "__name__", "")
    if name in {"date", "datetime"}:
        return "string"

    # Enums --------------------------------------------------------------
    if isinstance(annotation, EnumType):
        return annotation.__name__

    # Pydantic models ----------------------------------------------------
    if isinstance(annotation, type) and issubclass(annotation, BaseModel):
        return annotation.__name__

    # Generics: X | None, tuple[X, ...], list[X] -------------------------
    origin = get_origin(annotation)
    args = get_args(annotation)
    if origin is None:
        # Fallback — explicit so unhandled types fail loudly.
        raise TypeError(f"unhandled annotation: {annotation!r}")

    # Union (X | Y, X | None) — see _UNION_ORIGINS for cross-version rationale.
    if origin in _UNION_ORIGINS:
        rendered = sorted({_ts_type(a) for a in args if a is not type(None)})
        if type(None) in args:
            return f"{' | '.join(rendered)} | null"
        return " | ".join(rendered)

    # tuple[T, ...]  →  readonly T[]
    if origin is tuple:
        if len(args) == 2 and args[1] is Ellipsis:
            return f"readonly {_ts_type(args[0])}[]"
        return "[" + ", ".join(_ts_type(a) for a in args) + "]"

    # list[T] / Sequence[T]  →  readonly T[]
    if origin in (list,) or getattr(origin, "__name__", "") in {"Sequence", "list"}:
        return f"readonly {_ts_type(args[0])}[]"

    raise TypeError(f"unhandled origin {origin!r} for {annotation!r}")


# --------------------------------------------------------------------------
# Emitters
# --------------------------------------------------------------------------


def _emit_str_enum(enum_cls: EnumType) -> str:
    """Emit a TS string-literal union + a const lookup object."""
    members = list(enum_cls)
    union = " | ".join(f'"{m.value}"' for m in members)
    obj_lines = ",\n".join(f'  {m.name}: "{m.value}"' for m in members)
    return (
        f"export type {enum_cls.__name__} = {union};\n\n"
        f"export const {enum_cls.__name__} = {{\n{obj_lines},\n}} as const;\n"
    )


def _emit_model(model_cls: type[BaseModel]) -> str:
    """Emit a TS interface for a Pydantic model. Fields rendered in declaration order."""
    fields_src: list[str] = []
    for name, field in model_cls.model_fields.items():
        ts = _ts_type(field.annotation)
        # Optional fields (no default required) emit `field?:` for ergonomic TS.
        # Fields with `| null` keep both `?` and `| null` so callers can pass either.
        is_optional = not field.is_required()
        marker = "?" if is_optional else ""
        fields_src.append(f"  {name}{marker}: {ts};")
    return f"export interface {model_cls.__name__} {{\n" + "\n".join(fields_src) + "\n}\n"


# --------------------------------------------------------------------------
# Files
# --------------------------------------------------------------------------


def _render_regimes() -> str:
    out = [HEADER, _emit_str_enum(regimes.Regime)]
    # REGIME_COLORS is a Final[dict[Regime, str]]. Render as Readonly<Record<...>>.
    color_lines = ",\n".join(
        f'  {r.name}: "{regimes.REGIME_COLORS[r]}"' for r in regimes.Regime
    )
    out.append(
        "\nexport const REGIME_COLORS: Readonly<Record<Regime, string>> = {\n"
        f"{color_lines},\n}} as const;\n"
    )
    return "".join(out)


def _render_profiles() -> str:
    return "".join(
        [
            HEADER,
            _emit_str_enum(profiles.RiskTolerance),
            "\n",
            _emit_str_enum(profiles.IncomeNeed),
            "\n",
            _emit_str_enum(profiles.ProfileStyle),
            "\n",
            _emit_model(profiles.UserStrategyProfile),
        ]
    )


def _render_types() -> str:
    return "".join(
        [
            HEADER,
            _emit_str_enum(types.OptionType),
            "\n",
            _emit_model(types.OptionContract),
            "\n",
            _emit_model(types.ChainSnapshot),
        ]
    )


def _render_index() -> str:
    return (
        HEADER
        + 'export * from "./regimes";\n'
        + 'export * from "./profiles";\n'
        + 'export * from "./types";\n'
    )


FILES: dict[str, callable] = {  # type: ignore[type-arg]
    "regimes.ts": _render_regimes,
    "profiles.ts": _render_profiles,
    "types.ts": _render_types,
    "index.ts": _render_index,
}


# --------------------------------------------------------------------------
# CLI
# --------------------------------------------------------------------------


def main() -> int:
    check = "--check" in sys.argv[1:]
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    drift = False

    for name, render in FILES.items():
        target = OUT_DIR / name
        new = render()
        if check:
            existing = target.read_text() if target.exists() else ""
            if existing != new:
                drift = True
                print(f"DRIFT: {target.relative_to(_REPO_ROOT)}", file=sys.stderr)
                # Emit a unified diff so CI logs show exactly what differs.
                # Without this, debugging a drift failure means re-running locally.
                import difflib

                for line in difflib.unified_diff(
                    existing.splitlines(keepends=True),
                    new.splitlines(keepends=True),
                    fromfile=f"{target.name} (committed)",
                    tofile=f"{target.name} (regenerated)",
                    n=3,
                ):
                    sys.stderr.write(line)
                sys.stderr.write("\n")
        else:
            target.write_text(new)
            print(f"wrote {target.relative_to(_REPO_ROOT)}")

    if check and drift:
        print(
            "\nshared-types are out of sync with the engine. "
            "Run `python packages/shared-types/scripts/generate.py` and commit.",
            file=sys.stderr,
        )
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
